/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ABD-ELRAHMAN
 */
public class ManagerAddTrips extends javax.swing.JFrame {

    /**
     * Creates new form PassLogin
     */
    public ManagerAddTrips() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        BusRadioButton = new javax.swing.JRadioButton();
        limojRadioButton = new javax.swing.JRadioButton();
        minibusjRadioButton = new javax.swing.JRadioButton();
        oneWayjRadioButton = new javax.swing.JRadioButton();
        roundRadioButton5 = new javax.swing.JRadioButton();
        enternaljRadioButton = new javax.swing.JRadioButton();
        externalRadioButton = new javax.swing.JRadioButton();
        nonStopRadioButton = new javax.swing.JRadioButton();
        oneStopRadioButton = new javax.swing.JRadioButton();
        manyStopsjRadioButton = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(600, 600));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 21)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Previuos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText(" Destination :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Days :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Way :");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Stops :");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Vehicle :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("E-Kind :");

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));

        BusRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        BusRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        BusRadioButton.setText("Bus");
        BusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusRadioButtonActionPerformed(evt);
            }
        });

        limojRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        limojRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        limojRadioButton.setText("Limousine");
        limojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limojRadioButtonActionPerformed(evt);
            }
        });

        minibusjRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        minibusjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        minibusjRadioButton.setText("MiniBus");
        minibusjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minibusjRadioButtonActionPerformed(evt);
            }
        });

        oneWayjRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        oneWayjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        oneWayjRadioButton.setText("One-Way");
        oneWayjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneWayjRadioButtonActionPerformed(evt);
            }
        });

        roundRadioButton5.setBackground(new java.awt.Color(153, 255, 204));
        roundRadioButton5.setForeground(new java.awt.Color(0, 0, 0));
        roundRadioButton5.setText("Round");
        roundRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundRadioButton5ActionPerformed(evt);
            }
        });

        enternaljRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        enternaljRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        enternaljRadioButton.setText("Enternal");
        enternaljRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enternaljRadioButtonActionPerformed(evt);
            }
        });

        externalRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        externalRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        externalRadioButton.setText("External");
        externalRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalRadioButtonActionPerformed(evt);
            }
        });

        nonStopRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        nonStopRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        nonStopRadioButton.setText("Non-Stop");
        nonStopRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonStopRadioButtonActionPerformed(evt);
            }
        });

        oneStopRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        oneStopRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        oneStopRadioButton.setText("One-Stop");
        oneStopRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneStopRadioButtonActionPerformed(evt);
            }
        });

        manyStopsjRadioButton.setBackground(new java.awt.Color(153, 255, 204));
        manyStopsjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        manyStopsjRadioButton.setText("Many Stops");
        manyStopsjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manyStopsjRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BusRadioButton)
                                        .addGap(53, 53, 53)
                                        .addComponent(limojRadioButton))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(nonStopRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(oneStopRadioButton)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minibusjRadioButton)
                                    .addComponent(manyStopsjRadioButton)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oneWayjRadioButton)
                                    .addComponent(enternaljRadioButton))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(roundRadioButton5)
                                    .addComponent(externalRadioButton))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oneWayjRadioButton)
                    .addComponent(roundRadioButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enternaljRadioButton)
                    .addComponent(externalRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nonStopRadioButton)
                    .addComponent(oneStopRadioButton)
                    .addComponent(manyStopsjRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusRadioButton)
                    .addComponent(limojRadioButton)
                    .addComponent(minibusjRadioButton))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ManagerOption managerOption = new ManagerOption();
        this.setVisible(false);
        managerOption.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void oneWayjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneWayjRadioButtonActionPerformed
        if(oneWayjRadioButton.isSelected()){
            roundRadioButton5.setSelected(false);
        }
    }//GEN-LAST:event_oneWayjRadioButtonActionPerformed

    private void roundRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundRadioButton5ActionPerformed
        if(roundRadioButton5.isSelected()){
            oneWayjRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_roundRadioButton5ActionPerformed

    private void enternaljRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enternaljRadioButtonActionPerformed
        if(enternaljRadioButton.isSelected()){
            externalRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_enternaljRadioButtonActionPerformed

    private void externalRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalRadioButtonActionPerformed
        if(externalRadioButton.isSelected()){
            enternaljRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_externalRadioButtonActionPerformed

    private void nonStopRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonStopRadioButtonActionPerformed
        if(nonStopRadioButton.isSelected()){
           oneStopRadioButton.setSelected(false);
           manyStopsjRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_nonStopRadioButtonActionPerformed

    private void oneStopRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneStopRadioButtonActionPerformed
        if(oneStopRadioButton.isSelected()){
            nonStopRadioButton.setSelected(false);
            manyStopsjRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_oneStopRadioButtonActionPerformed

    private void manyStopsjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manyStopsjRadioButtonActionPerformed
        if(manyStopsjRadioButton.isSelected()){
            nonStopRadioButton.setSelected(false);
            oneStopRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_manyStopsjRadioButtonActionPerformed

    private void BusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusRadioButtonActionPerformed
        if(BusRadioButton.isSelected()){
            limojRadioButton.setSelected(false);
            minibusjRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_BusRadioButtonActionPerformed

    private void limojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limojRadioButtonActionPerformed
        if(limojRadioButton.isSelected()){
            BusRadioButton.setSelected(false);
            minibusjRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_limojRadioButtonActionPerformed

    private void minibusjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minibusjRadioButtonActionPerformed
        if(minibusjRadioButton.isSelected()){
            limojRadioButton.setSelected(false);
            BusRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_minibusjRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerAddTrips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerAddTrips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerAddTrips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerAddTrips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerAddTrips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BusRadioButton;
    private javax.swing.JRadioButton enternaljRadioButton;
    private javax.swing.JRadioButton externalRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton limojRadioButton;
    private javax.swing.JRadioButton manyStopsjRadioButton;
    private javax.swing.JRadioButton minibusjRadioButton;
    private javax.swing.JRadioButton nonStopRadioButton;
    private javax.swing.JRadioButton oneStopRadioButton;
    private javax.swing.JRadioButton oneWayjRadioButton;
    private javax.swing.JRadioButton roundRadioButton5;
    // End of variables declaration//GEN-END:variables
}
